import { Product } from './types';

export const products: Product[] = [
  {
    id: 'p1',
    title: 'Ryujin Dragon Knight',
    franchiseId: 'videojuegos',
    status: 'disponible',
    imageUrls: ['https://lh3.googleusercontent.com/aida-public/AB6AXuCJ5xdJ4G3KVHaLZtbxD8id_349Apy69eh2DzbzD74abcIHht368By8D1q7InsaeKXPzWwa_4WO6E3uoL6dpSwennTl9H6ycDNikESMfoMitccbUwbvlrwjQ4QYW2d806nuV4d_yFszGUSkM8APlUkconfmTS-AdqNg6GVdfe4YIgZJqOpIhKngw2LFJShgbbOr1Ulp6i3TUo08KUjC5dDw-JEW4h04CbbTOEfsDONDZhe2nhtjeaBxhQ'],
    finish: 'Hiperrealista',
    scale: ['1:6'],
    material: 'Resina',
    description: 'Detalles esculpidos en cota de malla, pedestal con dragón herido y acabado en azul real metálico.',
  },
  {
    id: 'p2',
    title: 'Ares Vanguard Paladin',
    franchiseId: 'anime',
    status: 'consultar',
    imageUrls: ['https://lh3.googleusercontent.com/aida-public/AB6AXuChlFYBO2Js4cr5RDnLUk6ntXgWeMIWK7pth__N_acIZ4RGyVSDjxuufCkl53jZt8n2_XziufcQ1E08Y2dDYs20lHRGveHZhYXzPQLN8K94OeLB32GPBrXcr05HHlPZ4Ag6gPrdOkI03mAaaD322j80eUBu4-SPc34xFGWyfwOiRgMLC-m_SizSvi7bNqPVuVWaopNro-XpjC7IelSj41eMP1bON0hNLhBuKU4jfW48ErO_8q7doz5phg'],
    finish: 'Anime',
    scale: ['1:4'],
    material: 'Resina + Pla',
    description: 'Armadura gótica completa con grabados heráldicos en oro y manto fluido en resina traslúcida.',
  },
  {
    id: 'p3',
    title: 'The Shadow Crusader',
    franchiseId: 'dc',
    status: 'disponible',
    imageUrls: ['https://lh3.googleusercontent.com/aida-public/AB6AXuDxJb8252wBpZI1Suz3gk7ovQs5pIrgN9VNSbdJh7FSPxgqmWEVhsytP-QXqaYxRF6oESiGZ_0hjhqyK8c66hFPKvIXXeNzBVMFPmTSD_4WfUjupUW9PA_hA3FB4HkTcc94LZ6C-rk_3nqWUy8Lg_uo7cLLW_lj9kUwtiz8hUU-W2qLvdIP-648NbCkH8hVI6XLmSoEtwxx8qoqujtc8MPkeSWTnUQWNYA90wzVdGjFCeFXjz7UwxnYeA'],
    finish: 'Comic',
    scale: ['1:4'],
    material: 'Resina',
    description: 'Pedestal con gárgola de catedral gótica, capa textil alambrada y ojos iluminados por fibra óptica sutil.',
  },
  {
    id: 'p4',
    title: 'Awakened Warrior Prime',
    franchiseId: 'anime',
    status: 'disponible',
    imageUrls: ['https://lh3.googleusercontent.com/aida-public/AB6AXuC35PZCZ-pxtrmIjqWhhkaHaskw2xrHusGu9IinGEXrnpveMmeoH1Z1xxqoqEvoh0fSdNKKsfY-nDpvyoqKzqqYEok42Nme3Q1lsoO0bTBSmUsHhAhHplgzcusPg0yOWE6wgEH4z4LOvuSfxe145SMhOVLS4AW8Y-InlYyzLMM-EKOLPnu55Eb2_cfZ4HE7d6vmRXvflhqyx4o5MW_Y2CAFO5kZBdn2wNZRJYzzX_tDbzhAyGfn8vIVog'],
    finish: 'Cell Shading',
    scale: ['1:6'],
    material: 'Resina',
    description: 'Resina translúcida para efecto de aura áurea, base de cráter con iluminación LED recargable.',
  },
  {
    id: 'p5',
    title: 'Titanium Mark LXXXV',
    franchiseId: 'marvel',
    status: 'consultar',
    imageUrls: ['https://lh3.googleusercontent.com/aida-public/AB6AXuAUdSMo8_qzzEyH1UTLhqLPKcOtG75BTi5ZyDkYA4iRT9ybf37oRNSxiOYmfE2Pb6w-0fvFcvqPwlBPSNjPJZN50xZzrnOQlwdtUiwD2tmzoE_4mg90MTo73uON_QWEhbCeaeGpumMNqfjDAJYFlUcFD8WrUYNtv_V_aqJWkszFP8YDu4ROwqHzn7_V11DSxFCYc8H0GNHDE3OWeP3_vM0W64eRxx-RCthvlEhDZUAxqJ-7sdX-x1886Q'],
    finish: 'Hiperrealista',
    scale: ['1:4'],
    material: 'Pla',
    description: 'Pintura automotriz candy apple con barniz cerámico anti-rayas y micro-reactores de arco luminosos.',
  },
  {
    id: 'p6',
    title: 'Kromium Drifter',
    franchiseId: 'cinema',
    status: 'proximamente',
    imageUrls: ['https://lh3.googleusercontent.com/aida-public/AB6AXuDpJpf7iW9y4_zztv6xqtsGdDx8Q2JW4K5F7xS83C4PiRn06VJg7nr7tcrhWL694OxViQllp6mpbcM4OafO9mp8nZTb4BoV_JQga0I8RYA6uUxH7Vz-vD2e_foG7cwtC5N8CjtZmF4SSq-RIiyswWz2-rscupCYLqMNzHjF43or3BL1__4i2GTGwApJt7N7b7Iv8n80ZdNasfgcCXlTLBj20I-tyPkOHYL6WnU3f-GtbPzb0EC_8m60TQ'],
    finish: 'Hiperrealista',
    scale: ['1:6'],
    material: 'Resina',
    description: 'Detallado táctico con desgaste realista, correas de cuero auténtico cosidas a escala y armamento modular.',
    badge: 'Próximamente',
  },
];
